package Clases;

public enum Genero {
	ACOUSTIC_POP, ART_POP, ATL_HIP_HOP, AUSTRALIAN_POP, BARBADIAN_POP, BAROQUE_POP, BIG_ROOM, BOY_BAND, BRITISH_SOUL, CANADIAN_HIP_HOP, CANADIAN_POP, CANDY_POP, CELTIC_ROCK, CHICAGO_RAP, COLOMBIAN_POP, COMPLEXTRO, DANCE_POP, DETROIT_HIP_HOP, ELECTRO, HIP_POP, INDIE_POP, NEO_MELLOW, PERMANENT_WAVE, POP;


}
