BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "USUARIO" (
	"ID"	INTEGER,
	"NICK"	TEXT NOT NULL,
	"GMAIL"	TEXT NOT NULL,
	"CONTRASEÑA"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "CANCION" (
	"ID_C"	INTEGER,
	"NOMBRE_C"	TEXT NOT NULL,
	"ARTISTA_C"	TEXT NOT NULL,
	"GENERO"	TEXT NOT NULL,
	"DURACION_C"	TEXT NOT NULL,
	"REPRODUCCIONES_C"	TEXT NOT NULL,
	"MEGUSTAS_C"	INTEGER NOT NULL,
	PRIMARY KEY("ID_C" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PODCAST" (
	"ID_P"	INTEGER,
	"NOMBRE_P"	TEXT NOT NULL,
	"ARTISTA_P"	TEXT NOT NULL,
	"TEMA"	TEXT NOT NULL,
	"DURACION_P"	TEXT NOT NULL,
	"REPRODUCCIONES_P"	INTEGER NOT NULL,
	"MEGUSTAS_P"	INTEGER NOT NULL,
	PRIMARY KEY("ID_P" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "FAVORITO" (
	"ID_U"	INTEGER,
	"NOMBRE_P"	TEXT,
	"NOMBRE_C"	TEXT,
	FOREIGN KEY("NOMBRE_P") REFERENCES "PODCAST"("NOMBRE_P"),
	FOREIGN KEY("ID_U") REFERENCES "USUARIO"("ID"),
	PRIMARY KEY("ID_U","NOMBRE_P","NOMBRE_C")
);
INSERT INTO "USUARIO" VALUES (0,'a','a','a');
INSERT INTO "USUARIO" VALUES (1,'unai','basterretxea','paco123');
COMMIT;
